### ISSUE TITLE
Add Annotation value in Node struct

### ISSUE THREAD

**Issue by 0xBB2B** [need-being/go-tree#1]

**Comment by need-being** [comment]
There is a consideration against a single annotation or a bunch of annotations. like
```go
Annotation  interface[]
Annotations map[string]interface{}
```

If we support a bunch of annotations, which struct should we pick? `map[string]string`, `map[interface{}]interface{}` or `map[string]interface{}`?

**Comment by 0xBB2B** [comment]
Thank you for your reply

Usually, I think `map[string]string` is good enough
`interface{}` will make the data uncontrollable
But `map[string]interface{}` Versatility will be better
so, I prefer `map[string]interface{}` more
